### ISSUE TITLE
February 7 in the json file is incorrect

### ISSUE THREAD

**Issue by glutenfreepy** [IshanMi/Stoicbot#1]
Hey Ishan!
Wanted to let you know that entry for "February 7" in the json file has an empty string for the key and incorrect content.  The way it currently looks is pasted below.  Thanks!  -Ed
"": {
        "title": "December 1st",
        "quote": "PRETEND TODAY IS THE END\u201cLet us prepare our minds as if we\u2019d come to the very end of life. Let us postpone nothing. Let usbalance life\u2019s books each day. . . . The one who puts the finishing touches on their life each dayis never short of time.\u201d",
        "quote_source": "\u2014SENECA, MORAL LETTERS, 101.7b\u20138a",
        "explanation": "ive each day as if it were your last\u201d is a clich\u00e9. Plenty say it, few actually do it. How reasonablewould that be anyway? Surely Seneca isn\u2019t saying to forsake laws and considerations\u2014to findsome orgy to join because the world is ending.A better analogy would be a soldier about to leave on deployment. Not knowing whether they\u2019ll returnor not, what do they do?They get their affairs in order. They handle their business. They tell their children or their family thatthey love them. They don\u2019t have time for quarreling or petty matters. And then in the morning they areready to go\u2014hoping to come back in one piece but prepared for the possibility that they might not.Let us live today that same way."
    },

**Comment by kirillmamaev** [comment]
This should be fixed with [https://github.com/IshanMi/Stoicbot/pull/2](https://github.com/IshanMi/Stoicbot/pull/2)

**Comment by bbelderbos** [comment]
@mamaevdev thanks, code looks good and merged it in

@glutenfreepy feel free to double-check on your end as well ...
